version: '3.8'

services:

  # Servicio para la aplicación
  batalla:
    build:
      context: .  # El Dockerfile está en la raíz del proyecto
    environment:
      - PYTHONUNBUFFERED=1 # Terminal
    tty: true  # Para habilitar la consola interactiva
    stdin_open: true
    networks:
      - monitoring

  app:
    build:
      context: .  # Cambiado de 'app_dockerfile/' a '.'
      dockerfile: app_dockerfile/Dockerfile  # Especificamos la ruta al Dockerfile
    ports:
      - "5000:5000"  # Puerto para la aplicación
    networks:
      - monitoring
  
  # Servicio para Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuración de Prometheus
    ports:
      - "9090:9090"  # Puerto para Prometheus UI
    networks:
      - monitoring

  # Servicio para Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # Mapea el puerto 3001 al 3000 de Grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data: {}
