{
 "title": "SimulatorExportedExternally",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Recursos del Sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitoreo de Recursos del Sistema",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "Uso de CPU {{label_name}}" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Memoria Virtual {{label_name}}" },
    {
     "expr": "process_resident_memory_bytes",
     "legendFormat": "Memoria Resident {{label_name}}"
    }
   ]
  },
  {
   "title": "Número de veces que se realizó la recolección de basura",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Generación 0",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_collections_total{generation=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribución de Recolección de Basura por Generación",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_collections_total{generation=\"0\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "python_gc_collections_total{generation=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "python_gc_collections_total{generation=\"2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generación 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_collections_total{generation=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generación 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_collections_total{generation=\"2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disparos acertados y fallados en el juego",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "Disparos acertados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "disparos_acertados_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de disparos realizados",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_requests_http_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disparos fallados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    { "expr": "disparos_fallados_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proporción de Disparos Acertados vs Fallados",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disparos_acertados_total", "legendFormat": "X {{label_name}}" },
    { "expr": "disparos_fallados_total", "legendFormat": "O {{label_name}}" }
   ]
  }
 ]
}