{
 "title": "SimulatorExportedExternally",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Latency Accumulative Chart",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket",
     "legendFormat": "{{le}} seconds"
    }
   ]
  },
  { "title": "Pi Value", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pi Convergency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum(InnerPoint_total)/sum(totalOfPoints_total))*4",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Points",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "areaM2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(InnerPoint_total)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Dice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Frecuency of 6's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "dice_flip_count_total{resultado=\"6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dice Probabilities Convergency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(dice_flip_count_total{resultado=\"4\"}) / sum(total_flips_of_dice_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(dice_flip_count_total{resultado=\"5\"}) / sum(total_flips_of_dice_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(dice_flip_count_total{resultado=\"6\"}) / sum(total_flips_of_dice_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(dice_flip_count_total{resultado=\"1\"}) / sum(total_flips_of_dice_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(dice_flip_count_total{resultado=\"2\"}) / sum(total_flips_of_dice_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(dice_flip_count_total{resultado=\"3\"}) / sum(total_flips_of_dice_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frecuency of 5's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "dice_flip_count_total{resultado=\"5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proportions on pie chart",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dice_flip_count_total{resultado=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dice_flip_count_total{resultado=\"2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dice_flip_count_total{resultado=\"3\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dice_flip_count_total{resultado=\"4\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dice_flip_count_total{resultado=\"5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "dice_flip_count_total{resultado=\"6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frecuency of 4's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "dice_flip_count_total{resultado=\"4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frecuency of 3's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "dice_flip_count_total{resultado=\"3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frecuency of 2's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "dice_flip_count_total{resultado=\"2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frecuency of 1's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "dice_flip_count_total{resultado=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Coins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Frecuency of Heads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    { "expr": "disparos_acertados_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Convergency of expected value",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 73 },
   "targets": [
    { "expr": "total_disparos_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Frecuency of Tails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    { "expr": "disparos_fallados_total", "legendFormat": "__auto" }
   ]
  }
 ]
}