name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/eric
  pull_request:
    branches:
      - main
      - develop
      - feature/eric

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies for Juego-Offline
      working-directory: ./Juego-Offline
      run: pip install -r requirements.txt

    - name: Run security audit for Juego-Offline
      working-directory: ./Juego-Offline
      run: pip-audit

    - name: Run Pytest tests for Juego-Offline
      working-directory: ./Juego-Offline
      run: pytest tests/


    - name: Run Behave BDD tests for Juego-Offline
      working-directory: ./Juego-Offline
      run: behave

    - name: Build and Deploy Docker Compose for Juego-Offline
      working-directory: ./Juego-Offline
      run: docker compose up --build -d


    - name: Install dependencies for Multijugador
      working-directory: ./Multijugador
      run: pip install -r requirements.txt

    - name: Run security audit for Multijugador
      working-directory: ./Multijugador
      run: pip-audit